name = "DelaySSAToolkit"
uuid = "d39380a9-d0d7-4ae6-ae63-0e8d8b7efa9e"
authors = ["Xiaoming Fu"]
version = "0.1.0"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"

[compat]
Documenter = "0.27"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
